station_id = "GIOS_LR"
dH_0=9.01
nodata=["-999", "NAN"]

["GIOS_LR_table.txt"]
format="TX"
skiprows=1
utc_offset=0
dh_bolt_u=0
dh_diver_u=0
dh_bolt_l=0
dh_diver_l=0
p_offset_u=0
p_offset_l=0
p_offset_a=0
columns=["time","t_air","rh_air","p_air","p_wtr_l",
	 "p_wtr_u","p_wtr_m","precip_cum",
	 "SKIP_8","SKIP_9","batt_v"]
