station_id = "watson_diver_upper"
dH_0=9.01
nodata=["-999", "NAN"]

["Baro-CB914_241114135522_CB914.csv"]
format="csv"
skiprows=1
last_good_data_line=11653
utc_offset=3
p_offset_a=0
columns=["m_point","s_num","time","p_air","SKIP"]

["Watson_Lower_Y5781_240930180840_Y5781.csv"]
format="csv"
skiprows=1
last_good_data_line=19653
utc_offset=3
dh_bolt_l=10.98
analog_dvr_scale=1
dh_diver_l=0
p_offset_l=0
columns=["m_point","s_num","time","p_wtr_l","t_wtr_l","con","SKIP","h_l_h_ref","sal"]

["Sdr.Str.^42882^06-11-07 16-27-21.MON"]
format="mon"
skiprows=67
last_good_data_line=15260
utc_offset=2
dh_bolt_u=12.66
dh_diver_u=1.15
p_offset_u=-16
columns=["time","p_wtr_u","t_wtr_u"]

["SDR.STRCTD^61514^08-05-07 23-44-11.MON"]
format="mon"
skiprows=4034
last_good_data_line=11801
utc_offset=3
dh_bolt_u=12.66
dh_diver_u=1.15
p_offset_u=-16
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["SDR.STRCTD^61514^08-09-23 01-29-54.MON"]
format="mon"
skiprows=689
last_good_data_line=9402
utc_offset=-1
dh_bolt_u=12.66
dh_diver_u=1.05
p_offset_u=-18
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["DELFT^85754^09-09-21 17-25-46.MON"]
format="mon"
skiprows=71
last_good_data_line=7629
utc_offset=-1
dh_bolt_u=12.66
dh_diver_u=1.25
p_offset_u=-17
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["bro_oevre2_101005103902_88034.CSV"]
format="csv"
skiprows=66
last_good_data_line=10430
utc_offset=3
dh_bolt_u=12.66
dh_diver_u=1.15
p_offset_u=-17
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["bro_oevre2_151029105158_88034.MON"]
format="mon"
skiprows=1973
last_good_data_line=9390
utc_offset=3
dh_bolt_u=12.66
dh_diver_u=1.15
p_offset_u=-17
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["bro_oevre2_131010215608_88034.CSV"]
format="csv"
skiprows=84
last_good_data_line=10721
utc_offset=3
dh_bolt_u=12.66
dh_diver_u=1.1
p_offset_u=-18
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["Kan_bridge_upper_CTD_150119122111_88034.CSV"]
format="csv"
skiprows=1290
last_good_data_line=8995
utc_offset=3
dh_bolt_u=12.66
dh_diver_u=1.08
p_offset_u=-17
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["Kan_bridge_upper_CTD_151221150629_88034.MON"]
format="mon"
skiprows=2552
last_good_data_line=10617
utc_offset=3
dh_bolt_u=12.66
dh_diver_u=1.25
p_offset_u=-17
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["ctd_161011185926_88034.MON"]
format="mon"
skiprows=2311
last_good_data_line=14030
utc_offset=0
dh_bolt_u=12.66
dh_diver_u=1.26
p_offset_u=-20
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["ctd_171004113646_88034.MON"]
format="mon"
skiprows=2465
last_good_data_line=14226
utc_offset=0
dh_bolt_u=12.66
dh_diver_u=1.24
p_offset_u=-20
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["ctd_190405132723_88034.MON"]
format="mon"
skiprows=4817
last_good_data_line=13170
utc_offset=0
dh_bolt_u=12.66
dh_diver_u=1.24
p_offset_u=-19
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["ctd_191112100840_88034.MON"]
format="mon"
skiprows=75
last_good_data_line=12402
utc_offset=0
dh_bolt_u=12.66
dh_diver_u=1.24
p_offset_u=3
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["watson-lower_201029142951_88034 (CTD UPPER).MON"]
format="mon"
skiprows=689
last_good_data_line=13199
utc_offset=0
dh_bolt_u=12.66
dh_diver_u=1.23
p_offset_u=2
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["CTD_X2441_211004120808_X2441.MON"]
format="mon"
skiprows=9173
last_good_data_line=39822
utc_offset=0
dh_bolt_u=12.66
dh_diver_u=1.2
p_offset_u=-1
columns=["time","p_wtr_u","t_wtr_u","c_wtr_u"]

["bro_oevre1_101005111651_B4392.CSV"]
format="csv"
skiprows=69
last_good_data_line=41543
utc_offset=3
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=-20
columns=["time","p_wtr_l","t_wtr_l"]

["sws_j4813_151029105722_J4813.MON"]
format="mon"
skiprows=3869
last_good_data_line=19177
utc_offset=3
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=-19
columns=["time","p_wtr_l","t_wtr_l"]

["bro_oevre2_121114225410_G4445.CSV"]
format="csv"
skiprows=246
last_good_data_line=42391
utc_offset=3
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=-25
columns=["time","p_wtr_l","t_wtr_l"]

["bro_oevre2_131010215606_G4445.CSV"]
format="csv"
skiprows=74
last_good_data_line=43449
utc_offset=3
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=-23
columns=["time","p_wtr_l","t_wtr_l"]

["Kan_bridge_lower_CERA_151221144600_G4445.MON"]
format="mon"
skiprows=4949
last_good_data_line=37204
utc_offset=3
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=-20
columns=["time","p_wtr_l","t_wtr_l"]

["Kan_bridge_lower_CERA_151221151011_B4392.MON"]
format="mon"
skiprows=4697
last_good_data_line=20826
utc_offset=3
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=-19
columns=["time","p_wtr_l","t_wtr_l"]

["cera_2016_161011184732_T8670.MON"]
format="mon"
skiprows=6221
last_good_data_line=43662
utc_offset=0
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=-19
columns=["time","p_wtr_l","t_wtr_l"]

["cera_2017_1_171004115606_U5402.MON"]
format="mon"
skiprows=5669
last_good_data_line=43867
utc_offset=0
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=-17
columns=["time","p_wtr_l","t_wtr_l"]

["watson-upper_201029142212_U5421 (CERA LOWER).MON"]
format="mon"
skiprows=1925
last_good_data_line=39451
utc_offset=0
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=2
columns=["time","p_wtr_l","t_wtr_l"]

["Watson-lower U5421_211004102310_U5421.MON"]
format="mon"
skiprows=9161
last_good_data_line=41706
utc_offset=0
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=0
columns=["time","p_wtr_l","t_wtr_l"]

["watson-lower u5421_221115094308_U5421.MON"]
format="mon"
skiprows=4013
last_good_data_line=22590
utc_offset=0
dh_bolt_l=10.98
dh_diver_l=0
p_offset_l=-2
columns=["time","p_wtr_l","t_wtr_l"]

["Kangerlussuaq^33065^07-04-14 13-36-27.MON"]
format="mon"
skiprows=53
last_good_data_line=3015
utc_offset=2
p_offset_a=-19
columns=["time","p_air","SKIP_3"]

["Kangerlussuaq^33065^08-05-07 23-57-12.MON"]
format="mon"
skiprows=1289
last_good_data_line=4122
utc_offset=3
p_offset_a=-25
columns=["time","p_air","SKIP_3"]

["KangerlussuaqBaro^33065^08-09-25 13-23-15.MON"]
format="mon"
skiprows=104
last_good_data_line=9882
utc_offset=-1
p_offset_a=-18
columns=["time","p_air","SKIP_3"]

["KangerlussuaqBaro.MON"]
format="mon"
skiprows=2174
last_good_data_line=10092
utc_offset=-1
p_offset_a=-18
columns=["time","p_air","SKIP_3"]

["kangerlussuaqbaro1_101005110003_33065.CSV"]
format="csv"
skiprows=54
last_good_data_line=10531
utc_offset=3
p_offset_a=-19
columns=["time","p_air","SKIP_3"]

["kangerlussuaqbaro1_111004012013_33065.CSV"]
format="csv"
skiprows=3294
last_good_data_line=19423
utc_offset=3
p_offset_a=-17
columns=["time","p_air","SKIP_3"]

["kangerlussuaqbaro1_extended_with_baro2.CSV"]
format="csv"
skiprows=54
last_good_data_line=20850
utc_offset=3
p_offset_a=-16
columns=["time","p_air","SKIP_3"]

["kangerlussuaqbaro2_131010215609_26162.CSV"]
format="csv"
skiprows=3306
last_good_data_line=21595
utc_offset=3
p_offset_a=-16
columns=["time","p_air","SKIP_3"]

["Kan_bridge_BARO_150119122112_26162.CSV"]
format="csv"
skiprows=2502
last_good_data_line=18631
utc_offset=3
dh_bolt=0
dh_diver=0
p_offset_a=-16
columns=["time","p_air","SKIP_3"]

["Kan_bridge_BARO_151221150148_26162.MON"]
format="mon"
skiprows=54
last_good_data_line=16830
utc_offset=3
p_offset_a=-20
columns=["time","p_air","SKIP_3"]

["baro_161011191237_26162.MON"]
format="mon"
skiprows=3137
last_good_data_line=21858
utc_offset=0
p_offset_a=-22
columns=["time","p_air","SKIP_3"]

["baro_171004114423_26162.MON"]
format="mon"
skiprows=2861
last_good_data_line=21961
utc_offset=0
p_offset_a=-23
columns=["time","p_air","SKIP_3"]

["baro_190405131701_26162.MON"]
format="mon"
skiprows=7181
last_good_data_line=19710
utc_offset=0
p_offset_a=-22.7
columns=["time","p_air","SKIP_3"]

["baro_191112102659_26162.MON"]
format="mon"
skiprows=68
last_good_data_line=18558
utc_offset=0
p_offset_a=0
columns=["time","p_air","SKIP_3"]

["baro_201027201057_26162.MON"]
format="mon"
skiprows=989
last_good_data_line=19753
utc_offset=0
p_offset_a=0
columns=["time","p_air","SKIP_3"]

["Baro-CB914_211004122728_CB914.MON"]
format="mon"
skiprows=9161
last_good_data_line=41706
utc_offset=0
p_offset_a=0
columns=["time","p_air","SKIP_3"]

["baro-cb914_221115084604_CB914.MON"]
format="mon"
skiprows=4013
last_good_data_line=22590
utc_offset=0
p_offset_a=0
columns=["time","p_air","SKIP_3"]

